---

- name: Copy files
  template:
    src: '{{ item.file }}.j2'
    dest: '/u01/software/{{ item.file }}'
    mode: 0644
    owner: oracle
    group: oinstall
  with_items:
    - { file: setup_roles.py }
    - { file: domain.properties }

- name: Create roles/groups
  shell: '. ~/.bash_profile && ${WLS_HOME}/common/bin/wlst.sh /u01/software/setup_roles.py'
  become: yes
  become_user: "oracle"
