---

- name: Copy domain.properties
  template:
    src: 'domain.properties.j2'
    dest: '/u01/software/domain.properties'
    mode: '0644'
    owner: "oracle"
    group: "oinstall"

- name: Copy scripts
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items:
     - { src: 'scripts/setup_security_realm.py', dest: '/u01/software/setup_security_realm.py', mode: '0755', owner: "oracle", group: "oinstall" }

- name: Create security realm
  shell: '. ~/.bash_profile && ${WLS_HOME}/common/bin/wlst.sh /u01/software/setup_security_realm.py'
  become: yes
  become_user: "oracle"