---

- name: Copy domain.properties
  template:
    src: 'domain.properties.j2'
    dest: '/u01/software/domain.properties'
    mode: '0644'
    owner: "oracle"
    group: "oinstall"

- name: Copy scripts
  copy:
    src: 'scripts/setup_datasources.py'
    dest: '/u01/software/setup_datasources.py'
    mode: '0755'
    owner: "oracle"
    group: "oinstall"

- name: Create datasources
  shell: '. ~/.bash_profile && ${WLS_HOME}/common/bin/wlst.sh /u01/software/setup_datasources.py'
  become: yes
  become_user: "oracle"