---
- name: (main/admin_password) Remove data directory
  file:
    path: '{{ domain_home }}/servers/AdminServer/data/'
    state: absent

- name: (main/admin_password) Update password
  shell: |
    . {{ domain_home }}/bin/setDomainEnv.sh &&
    java weblogic.security.utils.AdminAccount weblogic ${weblogic_admin_password} {{ domain_home }}/security
  environment:
    - weblogic_admin_password: '{{ weblogic_admin_password }}'

- name: (main/admin_password) Update boot.properties
  template:
    src: "boot.properties.j2"
    dest: "{{ domain_home }}/servers/AdminServer/security/boot.properties"
    mode: 0644
    owner: oracle
    group: oinstall