---
- name: Remove data directory
  become: yes
  become_user: oracle
  file:
    path: '{{ domain_home }}/servers/AdminServer/data/'
    state: absent

- name: Update password
  chdir: '{{ domain_home }}/security'
  shell: 'java weblogic.security.utils.AdminAccount weblogic ${weblogic_admin_password} .'
  environment:
    - weblogic_admin_password: '{{ weblogic_admin_password }}'

- name: Update boot.properties
  template:
    src: "boot.properties.j2"
    dest: "{{ domain_home }}/servers/AdminServer/security/boot.properties"
    mode: 0644
    owner: oracle
    group: oinstall