---

- name: (main/datasources) Temporarily install sqlplus to check database health
  become: yes
  become_user: root
  yum:
    name:
      - libaio
      - https://download.oracle.com/otn_software/linux/instantclient/oracle-instantclient-basic-linuxx64.rpm
      - https://download.oracle.com/otn_software/linux/instantclient/oracle-instantclient-sqlplus-linuxx64.rpm
    state: present

- name: (main/datasources) Wait for database to be up (max 6 hours)
  shell:
    cmd: |
      sqlplus -L "delius_pool/${database_password}@{{ database_url | regex_replace('^.*@', '') }}" <<EOF
      select 1 from dual;
      EOF
  environment:
    database_password: '{{ database_password }}'
  register: db_healthcheck
  until: db_healthcheck is success
  retries: 720
  delay: 30

- name: (main/datasources) Remove sqlplus
  become: yes
  become_user: root
  yum:
    name:
      - oracle-instantclient-sqlplus
      - oracle-instantclient-basic
      - libaio
    state: absent

- name: (main/datasources) Copy domain.properties
  template:
    src: domain.properties.j2
    dest: /u01/software/domain.properties
    mode: 0644

- name: (main/datasources) Copy scripts
  copy:
    src: scripts/setup_datasources.py
    dest: /u01/software/setup_datasources.py
    mode: 0755

- name: (main/datasources) Copy libs
  copy:
    src: files/xmlparserv2.jar
    dest: '{{ domain_home }}/lib/xmlparserv2.jar'
    mode: 0755

- name: (main/datasources) Create datasources
  shell: . ~/.bash_profile && ${WLS_HOME}/common/bin/wlst.sh /u01/software/setup_datasources.py
  environment:
    weblogic_admin_password: '{{ weblogic_admin_password }}'
    database_password: '{{ database_password }}'
