---

- name: (main/datasources) Wait for database to be up (max 6 hours)
  wait_for:
    host: '{{ primary_db_host }}'
    port: 1521
    sleep: 30
    timeout: 21600

- name: (main/datasources) Copy domain.properties
  template:
    src: domain.properties.j2
    dest: /u01/software/domain.properties
    mode: 0644

- name: (main/datasources) Copy scripts
  copy:
    src: scripts/setup_datasources.py
    dest: /u01/software/setup_datasources.py
    mode: 0755

- name: (main/datasources) Copy libs
  copy:
    src: files/xmlparserv2.jar
    dest: '{{ domain_home }}/lib/xmlparserv2.jar'
    mode: 0755

- name: (main/datasources) Create datasources
  shell: . ~/.bash_profile && ${WLS_HOME}/common/bin/wlst.sh /u01/software/setup_datasources.py

- environment:
    weblogic_admin_password: '{{ weblogic_admin_password }}'
    database_password: '{{ database_password }}'
    ps_database_password: "{{ lookup('aws_ssm', '/delius-perf/delius/delius-gdpr-database/db/admin_password', region=region) }}"

