---

- name: (main/deploy_ndelius) Download NDelius application
  when: s3_dependencies_bucket is defined
  aws_s3:
    bucket: "{{ s3_dependencies_bucket }}"
    object: /dependencies/delius-core/NDelius-{{ ndelius_version }}/NDelius-ear-{{ ndelius_version | regex_replace("\.", "_") }}.ear
    dest: /u01/software/NDelius-ear-{{ ndelius_version | regex_replace("\.", "_") }}.ear
    mode: get

- name: (main/deploy_ndelius) Copy local NDelius application
  when: s3_dependencies_bucket is not defined
  copy:
    src: s3/dependencies/delius-core/NDelius-{{ ndelius_version }}/NDelius-ear-{{ ndelius_version | regex_replace("\.", "_") }}.ear
    dest: /u01/software/NDelius-ear-{{ ndelius_version | regex_replace("\.", "_") }}.ear
    mode: 0644
    owner: oracle
    group: oinstall

- name: (main/deploy_ndelius) Copy scripts
  copy:
    src: scripts/deploy.py
    dest: /u01/software/deploy.py
    mode: 0644
    owner: oracle
    group: oinstall

- name: (main/deploy_ndelius) Deploy application
  shell: '. ~/.bash_profile && ${WLS_HOME}/common/bin/wlst.sh /u01/software/deploy.py {{ item.name }} {{ item.file }} {{ item.order }}'
  environment:
    weblogic_admin_password: '{{ weblogic_admin_password }}'
  become: yes
  become_user: oracle
  with_items:
    - {
      name: 'NDelius-ear-{{ ndelius_version | regex_replace("\.", "_") }}',
      file: 'NDelius-ear-{{ ndelius_version | regex_replace("\.", "_") }}.ear',
      order: 100
    }
