---

- name: (main/deploy_jspell) Download jspellhtml application
  aws_s3:
    bucket: "{{ s3_dependencies_bucket }}"
    object: /dependencies/jspellhtml/jspellhtml.war
    dest: /u01/software/jspellhtml.war
    mode: get

- name: (main/deploy_jspell) Create exploded war directory
  file:
    path: /u01/software/jspellhtml
    state: directory
    mode: 0755

- name: (main/deploy_jspell) Unzip jspellhtml application
  unarchive:
    src: /u01/software/jspellhtml.war
    dest: /u01/software/jspellhtml
    remote_src: yes

- name: (main/deploy_jspell) Apply whitelisted wordlist
  copy:
    src: 'English (GB)_white_list'
    dest: '/u01/software/jspellhtml/WEB-INF/jspell/English (GB)_white_list'

- name: (main/deploy_jspell) Deploy application
  shell: '. ~/.bash_profile && ${WLS_HOME}/common/bin/wlst.sh /u01/software/deploy.py {{ item.name }} {{ item.file }} {{ item.order }}'
  environment:
    weblogic_admin_password: '{{ weblogic_admin_password }}'
  with_items:
    - {
      name: 'jspellhtml',
      file: 'jspellhtml',
      order: 100
    }
