---

- name: (main/haproxy) Install repo
  become: yes
  yum:
    name: centos-release-scl
    state: present

- name: (main/haproxy) Install packages
  become: yes
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - rh-haproxy18-haproxy
    - rh-haproxy18-haproxy-syspaths

- name: (main/haproxy) Configure proxy
  become: yes
  template:
    src: haproxy.cfg.j2
    dest: /etc/opt/rh/rh-haproxy18/haproxy/haproxy.cfg

- name: (main/haproxy) Start proxy
  become: yes
  systemd:
    name: rh-haproxy18-haproxy
    state: restarted
    enabled: yes

- name: (main/haproxy) Copy scripts
  copy:
    src: scripts/wl_proxy_ssl.py
    dest: /u01/software/wl_proxy_ssl.py
    mode: 0755
    owner: oracle
    group: oinstall

- name: (main/haproxy) Enable WebLogic plugin support in console
  shell: '. ~/.bash_profile && ${WLS_HOME}/common/bin/wlst.sh /u01/software/wl_proxy_ssl.py'
  become: yes
  become_user: oracle
  environment:
    weblogic_admin_password: '{{ weblogic_admin_password }}'