---
# tasks file for ndelius

- name: (main) Debug vars
  debug:
    msg: "{{ vars }}"
    verbosity: 2

- name: (main) set tag to indicate deployment
  ec2_tag:
    region: "{{ region }}"
    resource: "{{ instance_id }}"
    state: present
    tags:
      ndelius_version: "Deploying"

- name: (main) Set WebLogic startup params
  include: wl_params.yml

- name: (main) Setup security realm
  include: security_realm.yml

- name: (main) Setup datasources
  when: setup_datasources
  include: datasources.yml

- name: (main) Apply NDelius configuration
  include: nd_config.yml

- name: (main) Deploy NDelius
  include: deploy_ndelius.yml

- name: (main) Start weblogic
  become: yes
  systemd:
    name: weblogic.service
    state: restarted
    enabled: yes
