---
# tasks file for ndelius

- name: Set WebLogic startup params
  include: wl_params.yml

- name: Setup security realm
  include: security_realm.yml

- name: Setup datasources
  when: setup_datasources
  include: datasources.yml

- name: Apply NDelius configuration
  include: nd_config.yml

- name: Deploy NDelius
  include: deploy_ndelius.yml

- name: Start weblogic
  become: yes
  systemd:
    name: weblogic.service
    state: restarted
    enabled: yes
