---
# tasks file for ndelius

- name: Setup security realm
  include: security_realm.yml

- name: Setup datasources
  include: datasources.yml

- name: Apply NDelius configuration
  include: nd_config.yml

- name: Deploy NDelius
  include: deploy_ndelius.yml