---

- name: (monitoring) Create script for pushing mbean info to cloudwatch
  template:
    src: update_metrics.sh.j2
    dest: /usr/bin/update_metrics
    mode: u+x

- name: (monitoring) Copy jmx cli tool
  copy:
    src: cmdline-jmxclient-0.10.3.jar
    dest: /u01/software/cmdline-jmxclient-0.10.3.jar
    mode: u+x

- name: (monitoring) Create a cron job to update metrics every minute
  cron:
    name: Update metrics
    job: update_metrics
    minute: '*'
    hour: '*'
    day: '*'
    month: '*'
    weekday: '*'