---

- name: (main/wl_params) Remove default MaxPermSize setting
  when: '"-XX:MaxPermSize" in jvm_mem_args'
  replace:
    path: '{{ domain_home }}/bin/setDomainEnv.sh'
    regexp: '"-XX:MaxPermSize=.+"'
    replace: '""'

- name: (main/wl_params) Set JVM args
  replace:
    path: '{{ domain_home }}/bin/setDomainEnv.sh'
    regexp: '"-Xms.+ -Xmx.+"'
    replace: '"{{ jvm_mem_args }}"'

- name: (main/wl_params) Set JVM args for WLST
  replace:
    path: '{{ wl_home }}/common/bin/commEnv.sh'
    regexp: '-Xms.+ -Xmx.+'
    replace: '-Xms1g -Xmx1g'

- name: (main/wl_params) Update JVM params for the domain
  lineinfile:
    path:         '{{ domain_home }}/bin/setDomainEnv.sh'
    insertbefore: '^JAVA_OPTIONS="\$\{JAVA_OPTIONS\}"'
    line:         'JAVA_OPTIONS="${JAVA_OPTIONS} {{ item }}"'
  with_items:
    - -XX:+UseG1GC
    - -Dcom.sun.management.jmxremote
    - -Dcom.sun.management.jmxremote.port=8000
    - -Dcom.sun.management.jmxremote.ssl=false
    - -Dcom.sun.management.jmxremote.authenticate=false
    - -DDMS_Protocol=https
    - -Duser.timezone=Europe/London
    - -Djava.protocol.handler.pkgs=com.sun.net.ssl.internal.www.protocol
    - -Dssl.SocketFactory.provider=com.sun.net.ssl.internal.SSLSocketFactoryImpl
    - -DUseSunHttpHandler=true