---
- name: (main/wl_params) Set JVM args
  replace:
    path: '{{ domain_home }}/bin/setDomainEnv.sh'
    regexp: '"-Xms.+ -Xmx.+"'
    replace: '"{{ jvm_mem_args }}"'

- name: (main/wl_params) Set JVM args for WLST
  replace:
    path: '{{ wl_home }}/common/bin/commEnv.sh'
    regexp: '-Xms.+ -Xmx.+'
    replace: '-Xms1g -Xmx1g'

- name: (main/wl_params) Update JVM params for the domain (G1GC, DMS_Protocol)
  lineinfile:
    path:         '{{ domain_home }}/bin/setDomainEnv.sh'
    insertbefore: '^JAVA_OPTIONS="\$\{JAVA_OPTIONS\}"'
    line:         'JAVA_OPTIONS="${JAVA_OPTIONS} -XX:+UseG1GC -DDMS_Protocol=https"'
