---
- name: Create SPG directory
  file:
    path: /u01/software/SPG
    state: directory
    owner: oracle
    group: oinstall
    mode: 0755

- name: Download ActiveMQ application
  when: s3_dependencies_bucket is defined
  aws_s3:
    bucket: "{{ s3_dependencies_bucket }}"
    object: /dependencies/delius-core/NDelius-{{ ndelius_version }}/SPG/activemq-rar-spg-{{ ndelius_version | regex_replace("\.", "_") }}.rar
    dest: /u01/software/SPG/activemq-rar-spg-{{ ndelius_version | regex_replace("\.", "_") }}.rar
    mode: get

- name: Copy local ActiveMQ application
  when: s3_dependencies_bucket is not defined
  copy:
    src: s3/dependencies/delius-core/NDelius-{{ ndelius_version }}/SPG/activemq-rar-spg-{{ ndelius_version | regex_replace("\.", "_") }}.rar
    dest: /u01/software/SPG/activemq-rar-spg-{{ ndelius_version | regex_replace("\.", "_") }}.rar
    owner: oracle
    group: oinstall
    mode: 0644

- name: Download NDeliusSPG application
  when: s3_dependencies_bucket is defined
  aws_s3:
    bucket: "{{ s3_dependencies_bucket }}"
    object: /dependencies/delius-core/NDelius-{{ ndelius_version }}/SPG/activemq-rar-spg-{{ ndelius_version | regex_replace("\.", "_") }}.rar
    dest: /u01/software/SPG/activemq-rar-spg-{{ ndelius_version | regex_replace("\.", "_") }}.rar
    mode: get

- name: Copy local NDeliusSPG application
  when: s3_dependencies_bucket is not defined
  copy:
    src: s3/dependencies/delius-core/NDelius-{{ ndelius_version }}/SPG/NDeliusSPG-ear-{{ ndelius_version | regex_replace("\.", "_") }}.ear
    dest: /u01/software/SPG/NDeliusSPG-ear-{{ ndelius_version | regex_replace("\.", "_") }}.ear
    owner: oracle
    group: oinstall
    mode: 0644

- name: Create activemq directory
  file:
    path: /u01/software/SPG/activemq
    state: directory
    owner: oracle
    group: oinstall
    mode: 0755

- name: Copy NDelius SPG Properties
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items:
  - { src: 'activemq/broker-config.xml', dest: '/u01/software/SPG/activemq/broker-config.xml', mode: '0644', owner: "oracle", group: "oinstall" }
  - { src: 'activemq/log4j.xml', dest: '/u01/software/SPG/activemq/log4j.xml', mode: '0644', owner: "oracle", group: "oinstall" }
  - { src: 'jaas.config', dest: '/u01/software/SPG/jaas.config', mode: '0644', owner: "oracle", group: "oinstall" }

- name: Apply ActiveMQ Properties
  shell: '. ~/.bash_profile &&
    cp -r /u01/software/SPG/activemq/ ${MW_HOME}/user_projects/domains/{{ domain_name }}/config/activemq/ '
  become: yes
  become_user: "oracle"

- name: Apply jaas config
  shell: '. ~/.bash_profile &&
  cp /u01/software/SPG/jaas.config ${MW_HOME}/user_projects/domains/{{ domain_name }}/jaas.config '
  become: yes
  become_user: "oracle"

- name: Write password.keyfile
  shell: "printf 'username=\npassword=\n' >> ${MW_HOME}/user_projects/domains/{{ domain_name }}/password.keyfile"

- name: Copy scripts
  copy:
    src: 'scripts/deploy_ndelius_spg.py'
    dest: '/u01/software/deploy_ndelius_spg.py'
    mode: '0644'
    owner: "oracle"
    group: "oinstall"

- name: Deploy NDelius application
  shell: '. ~/.bash_profile && ${WLS_HOME}/common/bin/wlst.sh /u01/software/deploy_ndelius_spg.py activemq-rar-spg-{{ ndelius_version | regex_replace("\.", "_") }}.rar 1 NDeliusSPG-ear-{{ ndelius_version | regex_replace("\.", "_") }}.ear 101'
  become: yes
  become_user: "oracle"
