---
- name: Create SPG directory
  file:
    path: /u01/software/SPG
    state: directory
    owner: oracle
    group: oinstall
    mode: 0755

- name: Download ActiveMQ application
  when: s3_dependencies_bucket is defined
  aws_s3:
    bucket: "{{ s3_dependencies_bucket }}"
    object: /dependencies/delius-core/NDelius-{{ ndelius_version }}/SPG/activemq-rar-spg-{{ ndelius_version | regex_replace("\.", "_") }}.rar
    dest: /u01/software/SPG/activemq-rar-spg-{{ ndelius_version | regex_replace("\.", "_") }}.rar
    mode: get

- name: Copy local ActiveMQ application
  when: s3_dependencies_bucket is not defined
  copy:
    src: s3/dependencies/delius-core/NDelius-{{ ndelius_version }}/SPG/activemq-rar-spg-{{ ndelius_version | regex_replace("\.", "_") }}.rar
    dest: /u01/software/SPG/activemq-rar-spg-{{ ndelius_version | regex_replace("\.", "_") }}.rar
    owner: oracle
    group: oinstall
    mode: 0644

- name: Download NDeliusSPG application
  when: s3_dependencies_bucket is defined
  aws_s3:
    bucket: "{{ s3_dependencies_bucket }}"
    object: /dependencies/delius-core/NDelius-{{ ndelius_version }}/SPG/NDeliusSPG-ear-{{ ndelius_version | regex_replace("\.", "_") }}.ear
    dest: /u01/software/SPG/NDeliusSPG-ear-{{ ndelius_version | regex_replace("\.", "_") }}.ear
    mode: get

- name: Copy local NDeliusSPG application
  when: s3_dependencies_bucket is not defined
  copy:
    src: s3/dependencies/delius-core/NDelius-{{ ndelius_version }}/SPG/NDeliusSPG-ear-{{ ndelius_version | regex_replace("\.", "_") }}.ear
    dest: /u01/software/SPG/NDeliusSPG-ear-{{ ndelius_version | regex_replace("\.", "_") }}.ear
    owner: oracle
    group: oinstall
    mode: 0644

- name: Create activemq directory
  file:
    path: /u01/software/SPG/activemq
    state: directory
    owner: oracle
    group: oinstall
    mode: 0755

- name: Grab hostname of server for activemq broker-config
  shell: hostname
  register: hostname

- name: Set client connector url for broker-config
  set_fact:
    activemq_externalClientConnector: "tcp://{{ hostname.stdout }}:61617"

- name: Copy NDelius SPG Properties
  template:
    src: "{{ item.file }}.j2"
    dest: "/u01/software/SPG/{{ item.file }}"
    mode: 0644
    owner: oracle
    group: oinstall
  with_items:
  - { file: activemq/broker-config.xml }
  - { file: activemq/log4j.xml }

- name: Copy NDelius SPG Properties
  copy:
    src: 'scripts/{{ item.file }}'
    dest: '/u01/software/SPG/{{ item.file }}'
    mode: 0644
    owner: oracle
    group: oinstall
  with_items:
  - { file: jaas.config }

- name: Copy scripts
  template:
    src: "{{ item.file }}.j2"
    dest: "/u01/software/{{ item.file }}"
    mode: 0644
    owner: oracle
    group: oinstall
  with_items:
    - { file: setup_roles.py }

- name: Copy scripts
  copy:
    src: 'scripts/{{ item.file }}'
    dest: '/u01/software/{{ item.file }}'
    mode: 0644
    owner: oracle
    group: oinstall
  with_items:
    - { file: deploy.py }

- name: Update setDomainEnv for jaas
  lineinfile:
    path:         '/u01/app/oracle/middleware/user_projects/domains/{{ domain_name }}/bin/setDomainEnv.sh'
    insertbefore: '^JAVA_OPTIONS="\$\{JAVA_OPTIONS\}"'
    line:         'JAVA_OPTIONS="${JAVA_OPTIONS} -Djava.security.auth.login.config=jaas.config "'

- name: Apply ActiveMQ Properties
  shell: '. ~/.bash_profile &&
    cp -r /u01/software/SPG/activemq/ ${MW_HOME}/user_projects/domains/{{ domain_name }}/config/activemq/ '
  become: yes
  become_user: "oracle"

- name: Apply jaas config
  shell: '. ~/.bash_profile &&
    cp /u01/software/SPG/jaas.config ${MW_HOME}/user_projects/domains/{{ domain_name }}/jaas.config '
  become: yes
  become_user: "oracle"

- name: Create global roles
  shell: '. ~/.bash_profile && ${WLS_HOME}/common/bin/wlst.sh /u01/software/setup_roles.py'
  environment:
    weblogic_admin_password: '{{ weblogic_admin_password }}'
  become: yes
  become_user: oracle

- name: Deploy application
  shell: '. ~/.bash_profile && ${WLS_HOME}/common/bin/wlst.sh /u01/software/deploy.py {{ item.name }} {{ item.file }} {{ item.order }}'
  environment:
    weblogic_admin_password: '{{ weblogic_admin_password }}'
  become: yes
  become_user: oracle
  with_items:
    - {
      name: 'activemq-rar-spg-{{ ndelius_version | regex_replace("\.", "_") }}',
      file: 'SPG/activemq-rar-spg-{{ ndelius_version | regex_replace("\.", "_") }}.rar',
      order: 1
    }
    - {
      name: 'NDeliusSPG-ear-{{ ndelius_version | regex_replace("\.", "_") }}',
      file: 'SPG/NDeliusSPG-ear-{{ ndelius_version | regex_replace("\.", "_") }}.ear',
      order: 101
    }